### ISSUE TITLE
No toggle on button in web hooks beta program

### ISSUE THREAD

**Issue by brtbt** [jonashaefele/audiopen-obsidian#1]
![image](https://github.com/jonashaefele/audiopen-obsidian/assets/4089964/79b3b028-0d5b-4ed3-b716-c76d4811324b)

**Comment by jonashaefele** [comment]
Hi @brtbt that seems like an issue with AudioPen. I didn't make AudioPen, I just created the plugin to sync it to Obsidian. 

Beta features like the webhooks and other personalisation features are only available for paid plans from what I remember. Did you sign up for the service, or are you on the free trial?

If the problem persists, reach out to Louis from AudioPen <hello@audiopen.ai> he's amazing at helping out.
